/// Flutter icons AppIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
///
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const IconData star = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData starEmpty =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData ok = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData cancel = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData plus = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData pencil = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData left = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData right = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData menu = const IconData(0xf008, fontFamily: _kFontFam);
  static const IconData grid = const IconData(0xf00a, fontFamily: _kFontFam);
  static const IconData gridEmpty =
      const IconData(0xf00b, fontFamily: _kFontFam);
  static const IconData download =
      const IconData(0xf02e, fontFamily: _kFontFam);
  static const IconData upload = const IconData(0xf02f, fontFamily: _kFontFam);
  static const IconData eye = const IconData(0xf082, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xf083, fontFamily: _kFontFam);
  static const IconData calendar =
      const IconData(0xf4c5, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xf50d, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xf512, fontFamily: _kFontFam);
  static const IconData lockOpen =
      const IconData(0xf513, fontFamily: _kFontFam);
}
